server:
  port: 8080

spring:
  application:
    name: java-app
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres-service:5432/javaappdb}
    username: ${DATABASE_USERNAME:javaapp}
    password: ${DATABASE_PASSWORD:password123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.example: INFO
    org.springframework: WARN
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Jaeger tracing configuration
opentracing:
  jaeger:
    service-name: java-app
    sampler:
      type: const
      param: 1
    reporter:
      log-spans: true
