apiVersion: v1
kind: Namespace
metadata:
  name: java-app-secure
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: java-app-sa
  namespace: java-app-secure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: java-app-secure
  name: java-app-role
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: java-app-rolebinding
  namespace: java-app-secure
subjects:
- kind: ServiceAccount
  name: java-app-sa
  namespace: java-app-secure
roleRef:
  kind: Role
  name: java-app-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: java-app-secrets
  namespace: java-app-secure
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzLXNlcnZpY2U6NTQzMi9qYXZhYXBwZGI=  # postgresql://postgres-service:5432/javaappdb
  database-username: amF2YWFwcA==  # javaapp
  database-password: cGFzc3dvcmQxMjM=  # password123
